### ISSUE TITLE
Wind points

### ISSUE THREAD

**Issue by Szponeiro** [pawel33332/DSJ-4-WindPoints#1]
Wind points w późniejszym czasie tez bedzię zmodyfikowany z subskrypcja?

**Comment by pawel33332** [comment]
Aktywowałem wersję beta: https://github.com/pawel33332/DSJ-4-WindPoints/releases/tag/WindPointsv12beta

**Comment by Szponeiro** [comment]
W którym dokładnie miejscu wkleić folder graphics?

**Comment by pawel33332** [comment]
Wklejamy folder tam gdzie jest DSJ4.exe

**Comment by Szponeiro** [comment]
jesli pokazuje mi sie blad ze system win nie moze odnalezc DSJ4.exe to nie wiem co moglbym zrobic

**Comment by pawel33332** [comment]
plik .a3x musi byc tez tam gdzie DSJ4.exe

**Comment by Szponeiro** [comment]
tak zrobiłem i niestety ten błąd dalej mam, coś musialem albo przeoczyc albo zle wkleic
