### ISSUE TITLE
WindPoints

### ISSUE THREAD

**Issue by sali3nt** [pawel33332/DSJ-4-WindPoints#2]
Siema, jak odpalam ten dodatek, to pisze mi, że upłynął czas mojej subskrypcji. Czy wiesz o co chodzi?

**Comment by pawel33332** [comment]
Projekt WinfPoints jest wstrzymany i zablokowany, muszę poprawić odczyt kierunku wiatru co jest bardzo trudne do wykonania.

**Comment by pawel33332** [comment]
Aktywowałem wersję beta: https://github.com/pawel33332/DSJ-4-WindPoints/releases/tag/WindPointsv12beta
