### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by MechLesny** [pawel33332/DSJ-4-WindPoints#7]
przy próbie odpalenia tego programu gdy już jestem w dsj4 i chcę wejść w skocznię to wyskakuje komunikat "unexpectered internal error" i wywala dsj'a. 
![reroror](https://github.com/pawel33332/DSJ-4-WindPoints/assets/160164276/a4d4f188-c3ff-4eae-9f14-41260361393c)

**Comment by pawel33332** [comment]
Prawdopodobnie uzywasz innej wersji niz 1.11.3
