### ISSUE TITLE
Brak odczytu kąta wiatru

### ISSUE THREAD

**Issue by M4T9889** [pawel33332/DSJ-4-WindPoints#9]
Program działa, mierzy siłę wiatru ale nie jest w stanie zmierzyć kąta wiatru przez co wypluwa zawsze wynik +1. Screen z programu po oddanym skoku:
![image](https://github.com/pawel33332/DSJ-4-WindPoints/assets/40645567/47111505-973a-49ad-93fd-6fcb54b42ce1)

**Comment by pawel33332** [comment]
Poproszę pełnego screena podczas gry w trybie treningu lub PŚ podczas skoku lub po skoku.

**Comment by M4T9889** [comment]
Problem rozwiazany, strzalka nie zmienila automatycznie podglądu i po przelaczeniu jej za pomoca (-) i (=) zaczelo dzialac poprawnie, po ponownym włączeniu gry poprzez program juz automatycznie ustawia sie poprawny widok

**Comment by M4T9889** [comment]
Problem rozwiazany, strzalka nie zmienila automatycznie podglądu i po przelaczeniu jej za pomoca (-) i (=) zaczelo dzialac poprawnie, po ponownym włączeniu gry poprzez program juz automatycznie ustawia sie poprawny widok
